version: 2.1
jobs:
  build:
    working_directory: ~/tmp 
    docker: 
      - image: circleci/node:8.9.3 # the primary container
    steps:
      - checkout # check out the code in the project directory
      - run: npm install
      - run: npm test
